Repository DMotivation/pf-01-react, pull requests merged in 2019-02, with the labels that each got.

#2 Add some new layout components
  public/index.html
  src/App.styled.ts
  src/Pages/+Shared/HeadTitle.ts
  src/Pages/+Shared/Layout/Main.styled.ts
  src/Pages/+Shared/Layout/Section.styled.ts
  src/Pages/+Shared/Layout/Section.tsx
  src/Pages/Home/Home.tsx
  src/Pages/Home/SectionMain.tsx
  tsconfig.json
Labels: enhancement

#17 feat: add sections home page
  src/Header/Header.styled.ts
  src/Header/Header.tsx
  src/Header/Links.tsx
  src/Header/Nav/index.ts
  src/Header/index.ts
  src/Layout/Main.tsx
  src/Pages/Home/Card/Card.styled.ts
  src/Pages/Home/Card/Card.tsx
  src/Pages/Home/Home.tsx
  src/Pages/Home/SectionMain.styled.ts
  src/Pages/Home/SectionMain.tsx
Labels: enhancement

#16 Feat: Minimal implementation of theme context
  src/App.tsx
  src/Styleguide/Buttons/Buttons.tsx
  src/Styleguide/GridSystem/Grid.styled.ts
  src/Theme/Theme.tsx
  src/Theme/Util.ts
  src/Theme/index.ts
  src/Theme/types.ts
Labels: enhancement, feature

#18 Feat: First iteration of button improvement
  src/Pages/+Shared/Button.styled.ts
  src/Pages/+Shared/Buttons/Button.styled.ts
  src/Pages/+Shared/Buttons/Button.tsx
  src/Pages/+Shared/Buttons/Util.ts
  src/Pages/+Shared/Buttons/index.ts
  src/Pages/+Shared/index.ts
  src/Styleguide/Buttons/Buttons.styled.ts
  src/Styleguide/Buttons/Buttons.tsx
  src/Theme/Theme.tsx
  src/Theme/Util.ts
  src/Theme/index.ts
  src/Theme/types.ts
Labels: enhancement

#20 tool: support absolute path in app
  package.json
  tsconfig.json
  tsconfig.paths.json
Labels: enhancement

#23 feat: breakpoint css
  src/Device/breakpoints.ts
  src/Device/device.ts
  src/Device/device.util.ts
  src/Device/index.ts
Labels: enhancement

#24 feat: first draft main section
  src/+Shared/Section/Section.styled.ts
  src/+Shared/Section/Section.tsx
  src/+Shared/Section/index.ts
  src/Device/device.util.ts
  src/Footer/Footer.styled.ts
  src/Footer/Footer.tsx
  src/Header/Header.styled.ts
  src/Header/Header.tsx
  src/Layout/Main.tsx
  src/Layout/Section.styled.ts
  src/Layout/Section.tsx
  src/Layout/index.ts
  src/Pages/Home/Card/Card.styled.ts
  src/Pages/Home/Home.tsx
  src/Pages/Home/MainSection/SectionMain.styled.ts
  src/Pages/Home/MainSection/SectionMain.tsx
  src/Pages/Home/SectionMain.styled.ts
  src/Pages/Home/SectionMain.tsx
  src/Pages/Home/ServicesSection/ServicesSection.styled.ts
  src/Pages/Home/ServicesSection/ServicesSection.tsx
  src/Styleguide/Page.tsx
Labels: enhancement

#35 Feat/rework section component
  README.md
  src/+Shared/CollapsePadding/CollapsePadding.styled.ts
  src/+Shared/CollapsePadding/CollapsePadding.tsx
  src/+Shared/CollapsePadding/index.ts
  src/+Shared/Section/Section.styled.ts
  src/+Shared/Section/Section.tsx
  src/Footer/Footer.tsx
  src/Header/Header.styled.ts
  src/Header/Header.tsx
  src/Pages/Home/MainSection/SectionMain.tsx
Labels: refactor

#34 Feat: Implement Panel component
  src/App.styled.ts
  src/Styleguide/Page.tsx
  src/Styleguide/Panels/Panels.styled.ts
  src/Styleguide/Panels/Panels.tsx
  src/Styleguide/Panels/Route.tsx
  src/Styleguide/Panels/index.ts
  src/Theme/Util.ts
  src/Theme/types.ts
  src/UI-Kits/Panel/Panel.styled.ts
  src/UI-Kits/Panel/Panel.tsx
  src/UI-Kits/Panel/Util.ts
  src/UI-Kits/Panel/index.ts
  src/UI-Kits/Typography/Typography.styled.ts
  src/UI-Kits/Typography/Typography.tsx
  src/UI-Kits/Typography/Util.ts
  src/UI-Kits/index.ts
Labels: enhancement
